#!/bin/bash

# first arg  : stating i
# second arg : ending i
# third arg  : number of processors
# fourth arg : output directory

orte-clean;

for ((i=$1; i <= $2; i++)); do
  mkdir -p $4/0$i;
  rm -rf $4/0$i/*.*;
  mpirun -np $3 python data_assimilation.py $4 $i;
done
